// models/ProcessedDeduction.js

const mongoose = require('mongoose');

const ProcessedDeductionSchema = new mongoose.Schema({
  // The unique ID generated by the Flutter app for each offline transaction.
  deductionId: {
    type: String,
    required: true,
    unique: true, // This ensures we can never process the same ID twice.
    index: true,
  },
  // The user this deduction belongs to.
  userId: {
    type: String,
    required: true,
    index: true,
  },
  processedAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('ProcessedDeduction', ProcessedDeductionSchema);